version: "2"
services:
  postgresql:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 15432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    env_file:
      - docker.env
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
